Repository Expurple/Stonks, pull requests merged in 2020-07, with the labels that each got.

#2 сделал тестовый датасет для OrderBook
  Logic/OrderBook.cpp
  Logic/OrderBook.h
  UI/Graphs/AllGraphs.h
  UI/Graphs/GraphBuilder.h
  UI/Graphs/MainGraph.h
Labels: enhancement

#4 реализовали построение и отрисовку стакана
  Logic/GraphsBuilder.cpp
  Logic/GraphsBuilder.h
  Logic/OrderBook.cpp
  MarketDepthGraph.cpp
  README.md
  Stonks.sln
  Stonks.vcxproj
  Stonks.vcxproj.filters
  UI/Graphs/AllGraphs.h
  UI/Graphs/GraphBuilder.h
  UI/Graphs/MainGraph.h
  UI/Graphs/MarketDepthGraph.h
  main.cpp
Labels: enhancement

#6 рефакторинг кода для окна
  Stonks.vcxproj
  Stonks.vcxproj.filters
  UI/StonksApp.cpp
  UI/StonksApp.h
  UI/StonksMainWindow.cpp
  UI/StonksMainWindow.h
  UI/StonksMainWindow.qrc
  UI/StonksMainWindow.ui
  main.cpp
Labels: refactoring

#8 работа с таблицей ордербука
  Logic/OrderBookTableModel.cpp
  Logic/OrderBookTableModel.h
  Stonks.vcxproj
  Stonks.vcxproj.filters
  UI/StonksMainWindow.cpp
  UI/StonksMainWindow.h
  UI/StonksMainWindow.ui
  main.cpp
Labels: enhancement

#10 реализовал автоматическое проведение сделок по новым ордерам
  Logic/GraphsBuilder.cpp
  Logic/Order.h
  Logic/OrderBookTableModel.cpp
  Logic/OrderBookTableModel.h
  main.cpp
Labels: enhancement, refactoring
